#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fetch the channel configuration
  ibm.blockchain_platform.channel_config:
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    ordering_service: "{{ ordering_service_name }}"
    identity: "{{ organization_old_admin_identity }}"
    msp_id: "{{ organization_msp_id }}"
    operation: fetch
    name: "{{ channel_name }}"
    path: original_config.bin
  changed_when: False

- name: Create a copy of the channel configuration
  copy:
    src: original_config.bin
    dest: updated_config.bin
  changed_when: False

- name: Update the organization in the channel
  ibm.blockchain_platform.channel_member:
    state: present
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    organization: "{{ organization_name }}"
    path: updated_config.bin

- name: Compute the channel configuration update
  ibm.blockchain_platform.channel_config:
    operation: compute_update
    name: "{{ channel_name }}"
    original: original_config.bin
    updated: updated_config.bin
    path: config_update.bin
  register: compute_update
  changed_when: False

- name: Sign the channel configuration update
  ibm.blockchain_platform.channel_config:
    operation: sign_update
    identity: "{{ organization_old_admin_identity }}"
    msp_id: "{{ organization_msp_id }}"
    name: "{{ channel_name }}"
    path: config_update.bin
  when: compute_update.path

- name: Apply the channel configuration update
  ibm.blockchain_platform.channel_config:
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    operation: apply_update
    ordering_service: "{{ ordering_service_name }}"
    identity: "{{ organization_old_admin_identity }}"
    msp_id: "{{ organization_msp_id }}"
    name: "{{ channel_name }}"
    path: config_update.bin
  when: compute_update.path
