#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for primary region
  include_tasks: create/primary-region.yml
  loop: "{{ regions }}"
  loop_control:
    index_var: region_index
    label: "{{ region.api_endpoint }}"
    loop_var: region
  when: region_index == 0

- name: Create components for secondary regions
  include_tasks: create/secondary-region.yml
  loop: "{{ regions }}"
  loop_control:
    index_var: region_index
    label: "{{ region.api_endpoint }}"
    loop_var: region
  when: region_index != 0
