#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if organization name not specified
  fail:
    msg: organization_name not specified or is empty
  when: not organization_name is defined or not organization_name

- name: Create endorsing organization
  include_tasks: create.yml
  when: state == "present"

- name: Delete endorsing organization
  include_tasks: delete.yml
  when: state == "absent"
