#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if project not specified
  fail:
    msg: project not specified or is empty
  when: not project is defined or not project

- name: Determine if project exists
  k8s_info:
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ project }}"
  register: project_info

- name: Determine if custom resource definitions exist
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ibpconsoles.ibp.com
  register: crds_info

- name: Delete console
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: "ibp.com/v1alpha2"
    kind: IBPConsole
    name: "{{ console }}"
  when: project_info.resources and crds_info.resources

- name: Delete operator
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ operator }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  when: project_info.resources

- name: Delete image secret
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: v1
    kind: Secret
    name: "{{ image_pull_secret }}"
  when: project_info.resources

- name: Delete cluster role binding
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: "{{ cluster_role_binding }}"
  when: project_info.resources

- name: Delete cluster role
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: "{{ cluster_role }}"
  when: project_info.resources

- name: Delete security context constraints
  k8s:
    state: absent
    namespace: "{{ project }}"
    api_version: security.openshift.io/v1
    kind: SecurityContextConstraints
    name: "{{ security_context_constraints }}"
  when: project_info.resources
