#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for an ordering organization
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ ordering_org_name }}"
    organization_msp_id: "{{ ordering_service_msp }}"
    ca_admin_enrollment_id: "{{ca_admin_enrollment_id}}"
    organization_admin_enrollment_id: "{{ organization_admin_enrollment_id }}"
    ordering_service_enrollment_id: "{{ ordering_service_enrollment_id }}"
    ordering_service_name: "{{ ordering_service_name }}"
    ordering_service_nodes: "{{ ordering_service_nodes }}"
    # These variables should be supplied using --extra-vars "@ordering-org-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # ca_admin_enrollment_secret: adminpw
    # organization_admin_enrollment_secret: orderingorgadminpw
    # ordering_service_enrollment_secret: orderingorgordererpw
  roles:
    - ibm.blockchain_platform.ordering_organization
