#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Export the ordering service
  hosts: localhost
  vars:
    # These variables should be supplied using --extra-vars "@ordering-org-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  tasks:
    - name: Get the ordering service
      ibm.blockchain_platform.ordering_service_info:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        name: Ordering Service
      register: result

    - name: Fail if the ordering service does not exist
      fail:
        msg: Ordering service does not exist
      when: not result.exists

    - name: Store the ordering service in a file
      copy:
        content: "{{ result.ordering_service | to_nice_json }}"
        dest: Ordering Service.json
