#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for an endorsing organization
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org2_name }}"
    organization_msp_id: "{{ org2_msp_id }}"
    ca_admin_enrollment_id: "{{ca_admin_enrollment_id}}"
    organization_admin_enrollment_id: "{{ organization_admin_enrollment_id }}"
    peer_enrollment_id: "{{ peer_enrollment_id }}"
    ca_name: "{{ org2_ca_name }}"
    peer_name: "{{ org2_peer_name }}"
    # These variables should be supplied using --extra-vars "@org2-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # ca_admin_enrollment_secret: adminpw
    # organization_admin_enrollment_secret: org2adminpw
    # peer_enrollment_secret: org2peerpw
  roles:
    - ibm.blockchain_platform.endorsing_organization
