#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Import the organization
  hosts: localhost
  vars:
    # These variables should be supplied using --extra-vars "@org1-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  tasks:
    - name: Import the organization
      ibm.blockchain_platform.external_organization:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        organization: "{{ lookup('file', 'Org2.json' )}}"