#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install chaincode
  hosts: localhost
  vars:
    # These variables should be supplied using --extra-vars "@org2-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  tasks:
    - name: Install the chaincode on the peer
      ibm.blockchain_platform.installed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ org2_peer_name }}"
        identity: "{{ org2_name }} Admin.json"
        msp_id: "{{ org2_msp_id }}"
        path: "{{ smart_contract_base_name }}@{{ smart_contract_version }}.cds"
