#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Delete components for an endorsing organization
  hosts: localhost
  vars:
    state: absent
    organization_name: Org2
    # These variables should be supplied using --extra-vars "@org2-vars.yml"
    # api_endpoint: https://ibp-console.example.org:32000
    # api_authtype: basic
    # api_key: xxxxxxxx
    # api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  roles:
    - ibm.blockchain_platform.endorsing_organization
