#
# SPDX-License-Identifier: Apache-2.0
#
---
extends: default
rules:
  comments: disable
  comments-indentation: disable
  line-length: disable
  truthy:
    allowed-values:
      - "True"
      - "true"
      - "False"
      - "false"
      - "Yes"
      - "yes"
      - "No"
      - "no"
