#
# SPDX-License-Identifier: Apache-2.0
#
---
namespace: ibm
name: blockchain_platform
version: 0.0.41
readme: README.md
authors:
  - Simon Stone
description: Ansible collection for building Hyperledger Fabric networks using the IBM Blockchain Platform
license:
  - Apache-2.0
tags:
  - ibm
  - enterprise
  - blockchain
  - dlt
  - hyperledger
  - fabric
  - blockchain
repository: https://github.com/IBM-Blockchain/ansible-collection
documentation: https://ibm-blockchain.github.io/ansible-collection/
homepage: https://www.ibm.com/cloud/blockchain-platform
issues: https://github.com/IBM-Blockchain/ansible-collection/issues
