#
# SPDX-License-Identifier: Apache-2.0
#
---
namespace: hyperledger
name: fabric_ansible_collection
version: 2.0.0
readme: README.md
authors:
  - Simon Stone/Matthew White
description: Ansible collection for building Hyperledger Fabric networks
license:
  - Apache-2.0
tags:
  - enterprise
  - blockchain
  - dlt
  - hyperledger
  - fabric
  - blockchain
repository: https://github.com/hyperledger-labs/fabric-ansible-collection
documentation: https://hyperledger-labs.github.io/fabric-ansible-collection
homepage: https://github.com/hyperledger-labs/fabric-ansible-collection
issues: https://github.com/hyperledger-labs/fabric-ansible-collection/issues
