#
# SPDX-License-Identifier: Apache-2.0
#
---
galaxy_info:
  author: Simon Stone & Matthew White
  description: Ansible role for deploying the IBM Hyperledger Fabric Support Offering into Red Hat OpenShift or Kubernetes
  license: Apache-2.0
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags: []
  min_ansible_version: "2.9"
