#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if architecture not specified
  fail:
    msg: arch not specified or is not one of "amd64"
  when: not arch is defined or not arch in ("amd64")

- name: Create custom resource definitions
  include_tasks: "{{ target }}/create.yml"
