#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if architecture not specified
  fail:
    msg: arch not specified or is not one of "amd64" or "s390x"
  when: not arch is defined or not arch in ("amd64", "s390x")

- name: Fail if image registry email not specified
  fail:
    msg: image_registry_email not specified or is empty
  when: not image_registry_email is defined or not image_registry_email

- name: Fail if image registry password not specified
  fail:
    msg: image_registry_password not specified or is empty
  when: not image_registry_password is defined or not image_registry_password

- name: Create custom resource definitions
  include_tasks: "{{ target }}/create.yml"
