#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if namespace not specified
  fail:
    msg: namespace not specified or is empty
  when: not namespace is defined or not namespace

- name: Determine if namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
  register: namespace_info

- name: Determine if console exists
  kubernetes.core.k8s_info:
    namespace: "{{ namespace }}"
    api_version: "ibp.com/v1alpha2"
    kind: IBPConsole
    name: "{{ console_name }}"
  register: existing_console

# deletion of existin config maps? Other roles do this,, but AFTER the console creation has started?

- name: Create console
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    resource_definition: "{{ lookup('template', 'k8s/hlf-operations-console.yaml.j2') }}"
    apply: yes
  register: create_console

- name: Wait for console deployment to exist
  kubernetes.core.k8s_info:
    namespace: "{{ namespace }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ console_name }}"
  register: console_deployment
  until: console_deployment.resources
  retries: "{{ wait_timeout }}"
  delay: 1

- name: Wait for console deployment to start
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ console_name }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  changed_when: False

- name: Print console URL
  debug:
    msg: IBM Blockchain Platform console available at "https://{{ namespace }}-{{ console_name }}-console.{{ console_domain }}"
