#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Deploy Opensource Console
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    state: present
    wait_timeout: 3600
  roles:
    - ibm.blockchain_platform.fabric_console
