#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Deploy Fabric Operations Console
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    state: present
    wait_timeout: 3600
  roles:
    - hyperledger.fabric-ansible-collection.fabric_console
