#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Clear ordering service nodes
  set_fact:
    ordering_service_nodes_in_region: 0

- name: Determine and set ordering service nodes
  set_fact:
    ordering_service_nodes_in_region: "{{ (ordering_service_nodes_in_region | int) + 1 }}"
  loop: "{{ range(0, ordering_service_nodes, 1) | list }}"
  when: region_index == (item % (regions | length))

- name: Clear ordering service zones
  set_fact:
    ordering_service_zones_in_region: []

- name: Determine and set ordering service zones
  set_fact:
    ordering_service_zones_in_region: "{{ (ordering_service_zones_in_region | default([])) + [zones[item % (zones | length)]] }}"
  loop: "{{ range(0, ordering_service_nodes_in_region | int, 1) | list }}"
  when: zones is defined and zones

- name: Delete ordering service nodes
  include_tasks: secondary-osn.yml
  loop: "{{ range(0, ordering_service_nodes_in_region | int, 1) | list }}"
  loop_control:
    index_var: node_index
