#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if organization MSP ID not specified
  fail:
    msg: organization_msp_id not specified or is empty
  when: not organization_msp_id is defined or not organization_msp_id

- name: Fail if certificate authority admin enrollment ID not specified
  fail:
    msg: ca_admin_enrollment_id not specified or is empty
  when: not ca_admin_enrollment_id is defined or not ca_admin_enrollment_id

- name: Fail if certificate authority admin enrollment secret not specified
  fail:
    msg: ca_admin_enrollment_secret not specified or is empty
  when: not ca_admin_enrollment_secret is defined or not ca_admin_enrollment_secret

- name: Fail if certificate authority database type is not PostgreSQL
  fail:
    msg: ca_db_type not specified or is not "postgres"
  when: not ca_db_type is defined or not ca_db_type in ("postgres")

- name: Fail if certificate authority database connection string not specified
  fail:
    msg: ca_db_datasource not specified or is empty
  when: not ca_db_datasource is defined or not ca_db_datasource

- name: Fail if certificate authority database TLS enabled not specified
  fail:
    msg: ca_db_tls_enabled not specified
  when: not ca_db_tls_enabled is defined

- name: Fail if certficate authority database TLS CA certificates not specified
  fail:
    msg: ca_db_tls_certfiles not specified or is empty
  when: (ca_db_tls_enabled) and (not ca_db_tls_certfiles is defined or not ca_db_tls_certfiles)

- name: Fail if certificate authority replicas not specified or zero
  fail:
    msg: ca_replicas not specified or is < 1
  when: not ca_replicas is defined or not ca_replicas

- name: Fail if organization admin enrollment ID not specified
  fail:
    msg: organization_admin_enrollment_id not specified or is empty
  when: not organization_admin_enrollment_id is defined or not organization_admin_enrollment_id

- name: Fail if organization admin enrollment secret not specified
  fail:
    msg: organization_admin_enrollment_secret not specified or is empty
  when: not organization_admin_enrollment_secret is defined or not organization_admin_enrollment_secret

- name: Fail if ordering service enrollment ID not specified
  fail:
    msg: ordering_service_enrollment_id not specified or is empty
  when: not ordering_service_enrollment_id is defined or not ordering_service_enrollment_id

- name: Fail if ordering service enrollment secret not specified
  fail:
    msg: ordering_service_enrollment_secret not specified or is empty
  when: not ordering_service_enrollment_secret is defined or not ordering_service_enrollment_secret

- name: Fail if ordering service nodes not specified or zero
  fail:
    msg: ordering_service_nodes not specified or is < 1
  when: not ordering_service_nodes is defined or not ordering_service_nodes

- name: Fail if zones not specified
  fail:
    msg: zones not specified or is empty
  when: not zones is defined or not zones

- name: Create certificate authority
  ibm.blockchain_platform.certificate_authority:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    name: "{{ ca_name }}"
    config_override:
      ca:
        registry:
          maxenrollments: -1
          identities:
            - name: "{{ ca_admin_enrollment_id }}"
              pass: "{{ ca_admin_enrollment_secret }}"
              type: client
              maxenrollments: -1
              attrs:
                hf.Registrar.Roles: "*"
                hf.Registrar.DelegateRoles: "*"
                hf.Revoker: true
                hf.IntermediateCA: true
                hf.GenCRL: true
                hf.Registrar.Attributes: "*"
                hf.AffiliationMgr: true
        db:
          type: "{{ ca_db_type }}"
          datasource: "{{ ca_db_datasource }}"
          tls:
            enabled: "{{ ca_db_tls_enabled }}"
            certfiles: "{{ ca_db_tls_certfiles }}"
    replicas: "{{ ca_replicas }}"
    resources: "{{ ca_resources | default(omit) }}"
    storage: "{{ ca_storage | default(omit) }}"
    version: "{{ ca_version | default(omit) }}"
    wait_timeout: "{{ wait_timeout | default(omit) }}"

- name: Enroll certificate authority admin
  ibm.blockchain_platform.enrolled_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    certificate_authority: "{{ ca_name }}"
    name: "{{ ca_name }} Admin"
    enrollment_id: "{{ ca_admin_enrollment_id }}"
    enrollment_secret: "{{ ca_admin_enrollment_secret }}"
    path: "{{ ca_admin_identity }}"

- name: Register the organization admin
  ibm.blockchain_platform.registered_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    certificate_authority: "{{ ca_name }}"
    registrar: "{{ ca_admin_identity }}"
    enrollment_id: "{{ organization_admin_enrollment_id }}"
    enrollment_secret: "{{ organization_admin_enrollment_secret }}"
    max_enrollments: -1
    type: admin

- name: Register the ordering service
  ibm.blockchain_platform.registered_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    certificate_authority: "{{ ca_name }}"
    registrar: "{{ ca_admin_identity }}"
    enrollment_id: "{{ ordering_service_enrollment_id }}"
    enrollment_secret: "{{ ordering_service_enrollment_secret }}"
    max_enrollments: -1
    type: orderer

- name: Enroll the organization admin
  ibm.blockchain_platform.enrolled_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    certificate_authority: "{{ ca_name }}"
    name: "{{ organization_name }} Admin"
    enrollment_id: "{{ organization_admin_enrollment_id }}"
    enrollment_secret: "{{ organization_admin_enrollment_secret }}"
    path: "{{ organization_admin_identity }}"
  register: org_admin

- name: Create organization
  ibm.blockchain_platform.organization:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    name: "{{ organization_name }}"
    msp_id: "{{ organization_msp_id }}"
    certificate_authority: "{{ ca_name }}"
    registrar: "{{ ca_admin_identity }}"
    admins:
      - "{{ org_admin.enrolled_identity.cert | default(omit) }}"

- name: Determine ordering service zones
  set_fact:
    ordering_service_zones_temp: "{{ (ordering_service_zones_temp | default([])) + [zones[item % (zones | length)]] }}"
  loop: "{{ range(0, ordering_service_nodes, 1) | list }}"
  when: ordering_service_zones is not defined

- name: Set ordering service zones
  set_fact:
    ordering_service_zones: "{{ ordering_service_zones_temp }}"
  when: ordering_service_zones is not defined

- name: Create ordering service
  ibm.blockchain_platform.ordering_service:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    api_timeout: "{{ api_timeout | default(omit) }}"
    name: "{{ ordering_service_name }}"
    msp_id: "{{ organization_msp_id }}"
    nodes: "{{ ordering_service_nodes }}"
    certificate_authority: "{{ ca_name }}"
    enrollment_id: "{{ ordering_service_enrollment_id }}"
    enrollment_secret: "{{ ordering_service_enrollment_secret }}"
    admin_certificates:
      - "{{ org_admin.enrolled_identity.cert | default(omit) }}"
    resources: "{{ ordering_service_resources | default(omit) }}"
    storage: "{{ ordering_service_storage | default(omit) }}"
    version: "{{ ordering_service_version | default(omit) }}"
    wait_timeout: "{{ wait_timeout | default(omit) }}"
    zones: "{{ ordering_service_zones }}"
