#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Creating CRDs
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/hyperledger-labs/fabric-operator.git/config/crd') }}"
  register: resultcrds

# Create the namespace for the operator
- name: Fail if namespace not specified
  fail:
    msg: namespace not specified or is empty
  when: not namespace is defined or not namespace

- name: Determine if namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
  register: namespace_info

- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          'pod-security.kubernetes.io/enforce': baseline
  when: not namespace_info.resources

# Create the Role based Access Control
- name: Create Role Based Access Control
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    resource_definition: "{{ lookup('template', 'templates/' + target + '/rbac/' + item) }}"
    apply: yes
  loop:
    - hlf-operator-clusterrole.yaml
    - hlf-operator-clusterrolebinding.yaml.j2
    - hlf-operator-serviceaccount.yaml

# create the manager
- name: Create Operator
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    resource_definition: "{{ lookup('template', 'templates/' + target + '/manager/' + item) }}"
    apply: yes
  loop:
    - hlf-operator-manager.yaml.j2

- name: Wait for operator
  shell: |
    kubectl -n {{ namespace }} rollout status deploy fabric-operator
  changed_when: false
