#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Fail if namespace not specified
  fail:
    msg: namespace not specified or is empty
  when: not namespace is defined or not namespace

- name: Determine if namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
  register: namespace_info

- name: Delete custom resource definitions
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
    - ibpcas.ibp.com
    - ibpconsoles.ibp.com
    - ibporderers.ibp.com
    - ibppeers.ibp.com
  when: namespace_info.resources

- name: Delete service
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Service
    name: "{{ webhook }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  when: namespace_info.resources

- name: Delete deployment
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Deployment
    name: "{{ webhook }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  when: namespace_info.resources

- name: Delete secrets
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Secret
    name: "{{ item }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
    - webhook-tls-cert
    - webhook-tls-key
  when: namespace_info.resources

- name: Delete role binding
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: "{{ role_binding }}"
  when: namespace_info.resources

- name: Delete role
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    name: "{{ role }}"
  when: namespace_info.resources

- name: Delete image secret
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Secret
    name: "{{ image_pull_secret }}"
  when: namespace_info.resources
