#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Determine if console exists
  kubernetes.core.k8s_info:
    namespace: "{{ project }}"
    api_version: "ibp.com/v1alpha2"
    kind: IBPConsole
    name: "{{ console_name }}"
  register: existing_console

# deletion of existin config maps? Other roles do this,, but AFTER the console creation has started?

- name: Create console
  kubernetes.core.k8s:
    state: present
    namespace: "{{ project }}"
    resource_definition: "{{ lookup('template', 'openshift/hlf-operations-console.yaml.j2') }}"
    apply: yes
  register: create_console

- name: Wait for console deployment to exist
  kubernetes.core.k8s_info:
    namespace: "{{ project }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ console_name }}"
  register: console_deployment
  until: console_deployment.resources
  retries: "{{ wait_timeout }}"
  delay: 1

- name: Wait for console deployment to start
  kubernetes.core.k8s:
    state: present
    namespace: "{{ project }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ console_name }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  changed_when: False

- name: Wait for console route to exist
  kubernetes.core.k8s_info:
    namespace: "{{ project }}"
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ console_name }}-console"
  register: console_route
  until: console_route.resources
  retries: "{{ wait_timeout }}"
  delay: 1

- name: Set console URL from console route
  set_fact:
    console_url: "https://{{ console_route.resources[0].spec.host }}"

- name: Wait for console route to start
  uri:
    url: "{{ console_url }}"
    status_code: "200"
    validate_certs: no
  register: result
  until: result.status == 200
  retries: "{{ wait_timeout }}"
  delay: 1

- name: Print console URL
  debug:
    msg: IBM Blockchain Platform console available at {{ console_url }}
