#
# SPDX-License-Identifier: Apache-2.0
#
---
name: PR Build
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build_collection:
    name: Build collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: pip install -Ur requirements.txt
      - name: Build collection artifact
        run: |
          VERSION=$(yq -r .version galaxy.yml)
          ansible-galaxy collection build
          mv ibm-blockchain_platform-${VERSION}.tar.gz ibm-blockchain_platform.tar.gz
      - name: Install collection
        run: |
          VERSION=$(yq -r .version galaxy.yml)
          ansible-galaxy collection install ibm-blockchain_platform.tar.gz
      - name: Lint collection
        run: |
          flake8 .
          ansible-lint

          shellcheck tutorial/*.sh
          yamllint .
      - name: Publish collection
        uses: actions/upload-artifact@v2
        with:
          name: Collection
          path: ibm-blockchain_platform.tar.gz

  build_documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: pip install -Ur requirements.txt
      - name: Build documentation
        run: |
          cd docs
          make
          cd ..
          tar cf documentation.tar.gz docs/build
      - name: Publish documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: documentation.tar.gz


  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: pip install -Ur requirements.txt
      - name: Build Docker image
        run: |
          VERSION=$(yq -r .version galaxy.yml)
          docker build -t ibmblockchain/fabric-ansible:${VERSION} .
          docker tag ibmblockchain/fabric-ansible:${VERSION} ibmblockchain/fabric-ansible:latest
          docker save ibmblockchain/fabric-ansible:${VERSION} ibmblockchain/fabric-ansible:latest | gzip -c > image.tar.gz
      - name: Publish Docker image
        uses: actions/upload-artifact@v2
        with:
          name: Docker image
          path: image.tar.gz
